export const COLUMN_MAPPING: Record<string, string> = {
  wiek_rozpoznania: 'wiek_rozpoznania',
  age_at_diagnosis: 'wiek_rozpoznania',
  opoznienie_rozpoznia: 'opoznienie_rozpoznia',
  delay: 'opoznienie_rozpoznia',
  manifestacja_miesno_szkiel: 'manifestacja_miesno_szkiel',
  musculoskeletal: 'manifestacja_miesno_szkiel',
  manifestacja_skora: 'manifestacja_skora',
  skin: 'manifestacja_skora',
  manifestacja_wzrok: 'manifestacja_wzrok',
  eye: 'manifestacja_wzrok',
  vision: 'manifestacja_wzrok',
  serce: 'manifestacja_sercowo_naczyniowy',
  heart: 'manifestacja_sercowo_naczyniowy',
  manifestacja_sercowo_naczyniowy: 'manifestacja_sercowo_naczyniowy',
  pokarmowy: 'manifestacja_pokarmowy',
  gi: 'manifestacja_pokarmowy',
  gastrointestinal: 'manifestacja_pokarmowy',
  manifestacja_pokarmowy: 'manifestacja_pokarmowy',
  nerki: 'manifestacja_nerki',
  kidneys: 'manifestacja_nerki',
  manifestacja_nerki: 'manifestacja_nerki',
  manifestacja_moczowo_plciowy: 'manifestacja_moczowo_plciowy',
  genitourinary: 'manifestacja_moczowo_plciowy',
  csn: 'manifestacja_zajecie_csn',
  cns: 'manifestacja_zajecie_csn',
  manifestacja_zajecie_csn: 'manifestacja_zajecie_csn',
  neuro: 'manifestacja_neurologiczny',
  neurological: 'manifestacja_neurologiczny',
  manifestacja_neurologiczny: 'manifestacja_neurologiczny',
  liczba_narzadow: 'liczba_zajetych_narzadow',
  liczba_zajetych_narzadow: 'liczba_zajetych_narzadow',
  organ_count: 'liczba_zajetych_narzadow',
  zaostrz_wymagajace_hospital: 'zaostrz_wymagajace_hospital',
  hospitalization: 'zaostrz_wymagajace_hospital',
  oit: 'zaostrz_wymagajace_oit',
  icu: 'zaostrz_wymagajace_oit',
  zaostrz_wymagajace_oit: 'zaostrz_wymagajace_oit',
  kreatynina: 'kreatynina',
  creatinine: 'kreatynina',
  eozynofilia_krwi_obwodowej_wartosc: 'eozynofilia_krwi_obwodowej_wartosc',
  eosinophilia: 'eozynofilia_krwi_obwodowej_wartosc',
  pulsy: 'pulsy',
  pulse_steroids: 'pulsy',
  czas_sterydow: 'czas_sterydow',
  steroid_duration: 'czas_sterydow',
  plazmaferezy: 'plazmaferezy',
  plasmapheresis: 'plazmaferezy',
  biopsja_wynik: 'biopsja_wynik',
  biopsy: 'biopsja_wynik',
  id: 'patient_id',
  patient_id: 'patient_id',
  id_pacjenta: 'patient_id',
};

export const DEFAULT_VALUES: Record<string, number> = {
  wiek_rozpoznania: 50,
  opoznienie_rozpoznia: 6,
  manifestacja_miesno_szkiel: 0,
  manifestacja_skora: 0,
  manifestacja_wzrok: 0,
  manifestacja_sercowo_naczyniowy: 0,
  manifestacja_pokarmowy: 0,
  manifestacja_nerki: 0,
  manifestacja_moczowo_plciowy: 0,
  manifestacja_zajecie_csn: 0,
  manifestacja_neurologiczny: 0,
  liczba_zajetych_narzadow: 2,
  zaostrz_wymagajace_hospital: 0,
  zaostrz_wymagajace_oit: 0,
  kreatynina: 100,
  eozynofilia_krwi_obwodowej_wartosc: 0,
  pulsy: 0,
  czas_sterydow: 12,
  plazmaferezy: 0,
  biopsja_wynik: 0,
};

export const RISK_LEVEL_PL: Record<string, string> = {
  low: 'Niskie',
  moderate: 'Umiarkowane',
  high: 'Wysokie',
};
