export const COLUMN_MAPPING: Record<string, string> = {
  wiek_rozpoznania: 'wiek_rozpoznania',
  wiek: 'wiek_rozpoznania',
  age: 'wiek_rozpoznania',
  age_at_diagnosis: 'wiek_rozpoznania',
  opoznienie_rozpoznia: 'opoznienie_rozpoznia',
  delay: 'opoznienie_rozpoznia',
  manifestacja_miesno_szkiel: 'manifestacja_miesno_szkiel',
  musculoskeletal: 'manifestacja_miesno_szkiel',
  manifestacja_skora: 'manifestacja_skora',
  skin: 'manifestacja_skora',
  manifestacja_wzrok: 'manifestacja_wzrok',
  eye: 'manifestacja_wzrok',
  vision: 'manifestacja_wzrok',
  serce: 'manifestacja_sercowo_naczyniowy',
  heart: 'manifestacja_sercowo_naczyniowy',
  manifestacja_sercowo_naczyniowy: 'manifestacja_sercowo_naczyniowy',
  pokarmowy: 'manifestacja_pokarmowy',
  gi: 'manifestacja_pokarmowy',
  gastrointestinal: 'manifestacja_pokarmowy',
  manifestacja_pokarmowy: 'manifestacja_pokarmowy',
  nerki: 'manifestacja_nerki',
  kidneys: 'manifestacja_nerki',
  manifestacja_nerki: 'manifestacja_nerki',
  manifestacja_moczowo_plciowy: 'manifestacja_moczowo_plciowy',
  genitourinary: 'manifestacja_moczowo_plciowy',
  csn: 'manifestacja_zajecie_csn',
  cns: 'manifestacja_zajecie_csn',
  manifestacja_zajecie_csn: 'manifestacja_zajecie_csn',
  neuro: 'manifestacja_neurologiczny',
  neurological: 'manifestacja_neurologiczny',
  manifestacja_neurologiczny: 'manifestacja_neurologiczny',
  oddechowy: 'manifestacja_oddechowy',
  respiratory: 'manifestacja_oddechowy',
  manifestacja_oddechowy: 'manifestacja_oddechowy',
  nos_ucho_gardlo: 'manifestacja_nos_ucho_gardlo',
  ent: 'manifestacja_nos_ucho_gardlo',
  manifestacja_nos_ucho_gardlo: 'manifestacja_nos_ucho_gardlo',
  liczba_narzadow: 'liczba_zajetych_narzadow',
  liczba_zajetych_narzadow: 'liczba_zajetych_narzadow',
  organ_count: 'liczba_zajetych_narzadow',
  kreatynina: 'kreatynina',
  creatinine: 'kreatynina',
  max_crp: 'max_crp',
  crp: 'max_crp',
  eozynofilia_krwi_obwodowej_wartosc: 'eozynofilia_krwi_obwodowej_wartosc',
  eosinophilia: 'eozynofilia_krwi_obwodowej_wartosc',
  pulsy: 'pulsy',
  pulse_steroids: 'pulsy',
  plazmaferezy: 'plazmaferezy',
  plasmapheresis: 'plazmaferezy',
  biopsja_wynik: 'biopsja_wynik',
  biopsy: 'biopsja_wynik',
  id: 'patient_id',
  patient_id: 'patient_id',
  id_pacjenta: 'patient_id',
};

/** Columns of the patient form, in the order used by the sample file and exports. */
export const PATIENT_COLUMNS = [
  'wiek_rozpoznania',
  'opoznienie_rozpoznia',
  'manifestacja_nerki',
  'manifestacja_oddechowy',
  'manifestacja_nos_ucho_gardlo',
  'manifestacja_sercowo_naczyniowy',
  'manifestacja_pokarmowy',
  'manifestacja_zajecie_csn',
  'manifestacja_neurologiczny',
  'manifestacja_miesno_szkiel',
  'manifestacja_skora',
  'manifestacja_wzrok',
  'manifestacja_moczowo_plciowy',
  'liczba_zajetych_narzadow',
  'kreatynina',
  'max_crp',
  'eozynofilia_krwi_obwodowej_wartosc',
  'pulsy',
  'plazmaferezy',
  'biopsja_wynik',
] as const;

export const BINARY_COLUMNS = new Set<string>([
  'manifestacja_nerki', 'manifestacja_oddechowy', 'manifestacja_nos_ucho_gardlo', 'manifestacja_sercowo_naczyniowy',
  'manifestacja_pokarmowy', 'manifestacja_zajecie_csn', 'manifestacja_neurologiczny', 'manifestacja_miesno_szkiel',
  'manifestacja_skora', 'manifestacja_wzrok', 'manifestacja_moczowo_plciowy', 'pulsy', 'plazmaferezy', 'biopsja_wynik',
]);

export const RISK_LEVEL_PL: Record<string, string> = {
  low: 'Niskie',
  moderate: 'Umiarkowane',
  high: 'Wysokie',
};
